name: golang test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  golang_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: setup go untuk testing
        uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - name: golang ci linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -E gofmt
      - name: run test
        run: go test ./..
